name: Build Typst document
on: [push, workflow_dispatch]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - name: Typst
        uses: lvignoli/typst-action@v0.1
        with:
          source_file: |
            resume.typ
      - name: Upload PDF file
        uses: actions/upload-artifact@v5.0.0
        with:
          name: PDFs
          path: |
            resume.pdf
      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} â€” ${{ env.DATE }}"
          files: "*.pdf"
